# Generated by Django 5.0.2 on 2026-02-22 21:58

import apps.authentification.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='Email utilisé pour la connexion', max_length=255, unique=True, verbose_name='Adresse email')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('matricule', models.CharField(blank=True, help_text='Matricule pour les étudiants', max_length=50, null=True, unique=True, verbose_name='Matricule étudiant')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('CHEF_SECTEUR', 'Chef de Secteur'), ('ADMIN', 'Administrateur'), ('LIVREUR', 'Livreur')], db_index=True, default='ETUDIANT', max_length=20, verbose_name='Rôle')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membre du staff')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('statut_kyc', models.CharField(choices=[('EN_ATTENTE', 'En attente de vérification'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut KYC')),
                ('date_soumission_kyc', models.DateTimeField(blank=True, null=True, verbose_name='Date soumission KYC')),
                ('date_verification_kyc', models.DateTimeField(blank=True, null=True, verbose_name='Date vérification KYC')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google ID')),
                ('photo_profil', models.URLField(blank=True, null=True, verbose_name='Photo de profil')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='VerificationKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_carte_recto', models.ImageField(help_text="Scan du recto de la carte d'étudiant", upload_to=apps.authentification.models.chemin_upload_kyc, verbose_name='Recto de la carte')),
                ('image_carte_verso', models.ImageField(blank=True, help_text='Scan du verso de la carte (optionnel)', null=True, upload_to=apps.authentification.models.chemin_upload_kyc, verbose_name='Verso de la carte')),
                ('selfie_etudiant', models.ImageField(blank=True, help_text='Selfie tenant la carte (optionnel mais recommandé)', null=True, upload_to=apps.authentification.models.chemin_upload_kyc, verbose_name='Selfie avec carte')),
                ('numero_carte', models.CharField(max_length=50, verbose_name='Numéro de carte')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif du rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
                ('verifie_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'CHEF_SECTEUR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vérification KYC',
                'verbose_name_plural': 'Vérifications KYC',
            },
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='authentific_email_639591_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['role'], name='authentific_role_a970d8_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['statut_kyc'], name='authentific_statut__6679df_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['matricule'], name='authentific_matricu_5a90b3_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationkyc',
            index=models.Index(fields=['utilisateur'], name='authentific_utilisa_e411c2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationkyc',
            index=models.Index(fields=['numero_carte'], name='authentific_numero__81dca6_idx'),
        ),
    ]
