# Generated by Django 5.0.2 on 2026-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de réinitialisation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='reset_token_expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration token'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='statut_kyc',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de vérification'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('NON_SOUMIS', 'Non soumis')], db_index=True, default='NON_SOUMIS', max_length=20, verbose_name='Statut KYC'),
        ),
    ]
