# Generated by Django 5.2.11 on 2026-03-19 18:33

import apps.authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_utilisateur_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationkyc',
            name='image_carte_recto',
            field=models.ImageField(blank=True, help_text="Scan du recto de la carte d'étudiant", null=True, upload_to=apps.authentification.models.chemin_upload_kyc, verbose_name='Recto de la carte'),
        ),
    ]
