# Generated by Django 5.0.2 on 2026-04-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_remove_kyc'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='utilisateur',
            name='authentific_matricu_5a90b3_idx',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='matricule',
        ),
    ]
