# Generated by Django 6.0.5 on 2026-05-30 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_add_universite_profils_vendeur_livreur'),
        ('authentification', '0005_remove_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='niveau_etude',
            field=models.CharField(blank=True, help_text='Ex: Licence 1, Licence 2, Master...', max_length=50, null=True, verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='universite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='administration.universite', verbose_name='Université'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant (Client)'), ('LIVREUR', 'Livreur'), ('VENDEUR_INTERIEUR', 'Vendeur intérieur'), ('VENDEUR_EXTERIEUR', 'Vendeur extérieur'), ('CHEF_SECTEUR', 'Chef de Secteur'), ('ADMIN_UNIVERSITAIRE', 'Administrateur universitaire'), ('ADMIN', 'Super Administrateur')], db_index=True, default='ETUDIANT', max_length=20, verbose_name='Rôle'),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(db_index=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('est_verifie', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_expiration', models.DateTimeField(verbose_name='Expiration')),
            ],
            options={
                'verbose_name': 'Vérification OTP',
                'verbose_name_plural': 'Vérifications OTP',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['telephone', 'est_verifie'], name='authentific_telepho_27638f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SanctionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('SUSPENSION', 'Suspension temporaire'), ('BANNISSEMENT', 'Bannissement définitif')], max_length=15, verbose_name='Type')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin (suspension)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Sanction active')),
                ('prononce_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_prononcees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['-date_debut'],
            },
        ),
    ]
