# Generated by Django 5.0.2 on 2026-08-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_add_roles_universite_otp_sanctions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=50, verbose_name='Numéro de carte étudiant')),
                ('image_carte_recto', models.ImageField(blank=True, null=True, upload_to='kyc/carte/', verbose_name='Carte — recto')),
                ('image_carte_verso', models.ImageField(blank=True, null=True, upload_to='kyc/carte/', verbose_name='Carte — verso')),
                ('selfie_etudiant', models.ImageField(blank=True, null=True, upload_to='kyc/selfie/', verbose_name='Selfie')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif du rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_verification', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_kyc', to=settings.AUTH_USER_MODEL)),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dossier KYC (carte étudiant)',
                'verbose_name_plural': 'Dossiers KYC (carte étudiant)',
                'ordering': ['-date_creation'],
            },
        ),
    ]
