# Generated by Django 5.0.2 on 2026-02-22 21:58

import apps.commandes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(db_index=True, default=apps.commandes.models.generer_numero_commande, editable=False, max_length=20, unique=True, verbose_name='Numéro commande')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée - Paiement reçu'), ('REJETEE', 'Rejetée'), ('PRETE', 'Prête pour distribution'), ('DISTRIBUEE', 'Distribuée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total HT')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total TTC')),
                ('description_besoin', models.TextField(blank=True, help_text='Instructions spéciales pour la commande', null=True, verbose_name='Description du besoin')),
                ('heure_souhaitee', models.TimeField(blank=True, null=True, verbose_name='Heure souhaitée')),
                ('methode_paiement', models.CharField(choices=[('MOOV', 'Moov Money'), ('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money')], max_length=10, verbose_name='Méthode de paiement')),
                ('telephone_paiement', models.CharField(help_text='Numéro utilisé pour le paiement', max_length=20, verbose_name='Téléphone de paiement')),
                ('reference_paiement', models.CharField(blank=True, help_text='Référence de la transaction Mobile Money', max_length=100, null=True, verbose_name='Référence transaction')),
                ('capture_paiement', models.ImageField(blank=True, help_text="Capture d'écran de la transaction", null=True, upload_to='preuves_paiement/', verbose_name='Capture paiement')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif du rejet')),
                ('date_distribution', models.DateTimeField(blank=True, null=True, verbose_name='Date de distribution')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('ip_creation', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création')),
                ('distribue_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'LIVREUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_distribuees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_etudiant', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='administration.salle')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='administration.secteur')),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['CHEF_SECTEUR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée - Paiement reçu'), ('REJETEE', 'Rejetée'), ('PRETE', 'Prête pour distribution'), ('DISTRIBUEE', 'Distribuée'), ('ANNULEE', 'Annulée')], max_length=20, null=True, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée - Paiement reçu'), ('REJETEE', 'Rejetée'), ('PRETE', 'Prête pour distribution'), ('DISTRIBUEE', 'Distribuée'), ('ANNULEE', 'Annulée')], max_length=20, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_modification', models.DateTimeField(auto_now_add=True, verbose_name='Date modification')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='commandes.commande')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique commande',
                'verbose_name_plural': 'Historiques commandes',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Sous-total')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.produit')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.variante')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='OptionLigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_applique', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix appliqué')),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='commandes.lignecommande')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.option')),
            ],
            options={
                'verbose_name': 'Option de ligne',
                'verbose_name_plural': 'Options de ligne',
            },
        ),
        migrations.CreateModel(
            name='ClotureJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cloture', models.DateField(db_index=True, verbose_name='Date de clôture')),
                ('nombre_commandes', models.PositiveIntegerField(verbose_name='Nombre de commandes')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant total')),
                ('commandes_validees', models.PositiveIntegerField(default=0, verbose_name='Commandes validées')),
                ('commandes_rejetees', models.PositiveIntegerField(default=0, verbose_name='Commandes rejetées')),
                ('commandes_distribuees', models.PositiveIntegerField(default=0, verbose_name='Commandes distribuées')),
                ('resume_commandes', models.JSONField(default=dict, verbose_name='Résumé des commandes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('est_verrouillee', models.BooleanField(default=True, help_text="Une fois verrouillée, aucune modification n'est possible", verbose_name='Clôture verrouillée')),
                ('cloture_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clotures_effectuees', to=settings.AUTH_USER_MODEL)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clotures', to='administration.secteur')),
            ],
            options={
                'verbose_name': 'Clôture journalière',
                'verbose_name_plural': 'Clôtures journalières',
                'ordering': ['-date_cloture'],
                'indexes': [models.Index(fields=['date_cloture', 'secteur'], name='commandes_c_date_cl_650aca_idx')],
                'unique_together': {('secteur', 'date_cloture')},
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['numero_commande'], name='commandes_c_numero__ab62be_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='commandes_c_statut_7ba50d_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date_creation'], name='commandes_c_date_cr_bb1739_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['etudiant', 'statut'], name='commandes_c_etudian_d7fb59_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['secteur', 'statut'], name='commandes_c_secteur_65faca_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['salle', 'statut'], name='commandes_c_salle_i_16161a_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date_creation', 'secteur'], name='commandes_c_date_cr_d4ce9b_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquecommande',
            index=models.Index(fields=['commande', 'date_modification'], name='commandes_h_command_faaf80_idx'),
        ),
    ]
