# Generated by Django 5.0.2 on 2026-03-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(choices=[('MOOV', 'Moov Money'), ('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money'), ('SENFENICO', 'Senfenico')], max_length=10, verbose_name='Méthode de paiement'),
        ),
    ]
