# Generated by Django 5.0.2 on 2026-03-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_update_methode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Frais de livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_paiement',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Frais de paiement'),
        ),
    ]
