# Generated by Django 6.0.5 on 2026-05-30 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_qrcodecommande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='acceptee_par_vendeur',
            field=models.BooleanField(default=False, verbose_name='Acceptée par vendeur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_acceptation_livreur',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date acceptation livreur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_acceptation_vendeur',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date acceptation vendeur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur_assigne',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'LIVREUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_acceptees', to=settings.AUTH_USER_MODEL, verbose_name='Livreur assigné'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée par le vendeur'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('VALIDEE', 'Validée - Paiement reçu'), ('DISTRIBUEE', 'Distribuée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historiquecommande',
            name='ancien_statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée par le vendeur'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('VALIDEE', 'Validée - Paiement reçu'), ('DISTRIBUEE', 'Distribuée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], max_length=20, null=True, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='historiquecommande',
            name='nouveau_statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée par le vendeur'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('VALIDEE', 'Validée - Paiement reçu'), ('DISTRIBUEE', 'Distribuée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], max_length=20, verbose_name='Nouveau statut'),
        ),
        migrations.CreateModel(
            name='WalletVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde disponible (FCFA)')),
                ('total_encaisse', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total encaissé')),
                ('total_commissions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total commissions prélevées')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vendeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Wallet vendeur',
                'verbose_name_plural': 'Wallets vendeurs',
            },
        ),
        migrations.CreateModel(
            name='TransactionWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('CREDIT', 'Crédit (vente livrée)'), ('DEBIT', 'Débit (retrait)'), ('REMBOURSEMENT', 'Remboursement client')], max_length=15, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission Ritôtô')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_wallet', to='commandes.commande')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='commandes.walletvendeur')),
            ],
            options={
                'verbose_name': 'Transaction wallet',
                'verbose_name_plural': 'Transactions wallet',
                'ordering': ['-date_creation'],
            },
        ),
    ]
