# Generated by Django 5.0.2 on 2026-08-28 16:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_produit_vendeur_profillivreur_boutiques_attribuees_and_more'),
        ('commandes', '0010_add_statuts_mission_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code_retrait',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Code de retrait'),
        ),
        migrations.AddField(
            model_name='commande',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='administration.creneaulivraison', verbose_name='Créneau'),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_reception',
            field=models.CharField(choices=[('SUR_PLACE', 'Retrait sur place'), ('LIVRAISON', 'Livraison')], default='LIVRAISON', max_length=10, verbose_name='Mode de réception'),
        ),
        migrations.AddField(
            model_name='commande',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='administration.profilvendeur', verbose_name='Vendeur'),
        ),
        migrations.AddField(
            model_name='plainte',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Auteur du signalement'),
        ),
        migrations.AddField(
            model_name='plainte',
            name='photo_preuve',
            field=models.ImageField(blank=True, null=True, upload_to='plaintes/', verbose_name='Photo (preuve)'),
        ),
        migrations.AddField(
            model_name='walletvendeur',
            name='solde_en_attente',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Crédité au paiement, non retirable tant que la livraison n'est pas validée (§5.1)", max_digits=14, verbose_name='Solde en attente (FCFA)'),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='categorie',
            field=models.CharField(choices=[('COMMANDE', 'Problème de commande'), ('LIVRAISON', 'Problème de livraison'), ('PAIEMENT', 'Problème de paiement'), ('PRODUIT', 'Problème de produit'), ('PRODUIT_NON_RECU', 'Produit non reçu'), ('PRODUIT_DIFFERENT', 'Produit différent'), ('LIVREUR_INJOIGNABLE', 'Livreur injoignable'), ('PAIEMENT_NON_VALIDE', 'Paiement débité sans validation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='transactionwallet',
            name='type_transaction',
            field=models.CharField(choices=[('CREDIT_ATTENTE', 'Crédit en attente (paiement reçu)'), ('CREDIT', 'Crédit disponible (vente livrée)'), ('DEBIT', 'Débit (retrait)'), ('REMBOURSEMENT', 'Remboursement client')], max_length=15, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='NoteLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_livreurs_donnees', to=settings.AUTH_USER_MODEL)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_livreur', to='commandes.commande')),
                ('livreur', models.ForeignKey(limit_choices_to={'role': 'LIVREUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note livreur',
                'verbose_name_plural': 'Notes livreurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NoteVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_vendeurs_donnees', to=settings.AUTH_USER_MODEL)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_vendeur', to='commandes.commande')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='administration.profilvendeur')),
            ],
            options={
                'verbose_name': 'Note vendeur',
                'verbose_name_plural': 'Notes vendeurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('motif', models.TextField(blank=True, default='', verbose_name='Motif')),
                ('automatique', models.BooleanField(default=False, help_text='True : annulation avant préparation ou rupture de stock. False : décision admin.', verbose_name='Déclenché automatiquement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('TRAITE', 'Remboursé'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='commandes.commande')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
