# Generated by Django 5.0.2 on 2026-02-22 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Horaire actif')),
                ('limite_commandes', models.PositiveIntegerField(blank=True, help_text='Nombre max de commandes pour ce créneau', null=True, verbose_name='Limite de commandes')),
            ],
            options={
                'verbose_name': 'Horaire de commande',
                'verbose_name_plural': 'Horaires de commande',
                'ordering': ['secteur', 'jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Piment, Mayonnaise, Fromage', max_length=100, verbose_name="Nom de l'option")),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix additionnel')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Option active')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['produit', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description')),
                ('categorie', models.CharField(choices=[('SANDWICH', 'Sandwich'), ('BOISSON', 'Boisson'), ('PATISSERIE', 'Pâtisserie'), ('SNACK', 'Snack'), ('AUTRE', 'Autre')], db_index=True, default='AUTRE', max_length=20, verbose_name='Catégorie')),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de base')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image du produit')),
                ('est_actif', models.BooleanField(db_index=True, default=True, verbose_name='Produit actif')),
                ('stock_limite', models.BooleanField(default=False, verbose_name='Stock limité')),
                ('quantite_stock', models.PositiveIntegerField(blank=True, help_text='Renseigner si stock limité', null=True, verbose_name='Quantité en stock')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code salle')),
                ('capacite', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité')),
                ('etage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Étage')),
                ('batiment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bâtiment')),
                ('est_actif', models.BooleanField(db_index=True, default=True, verbose_name='Salle active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['secteur__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du secteur')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code secteur')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('est_actif', models.BooleanField(db_index=True, default=True, verbose_name='Secteur actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Petit, Grand, Moyen', max_length=100, verbose_name='Nom de la variante')),
                ('ajustement_prix', models.DecimalField(decimal_places=2, default=0, help_text='Prix additionnel par rapport au prix de base', max_digits=10, verbose_name='Ajustement prix')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Variante active')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['produit', 'nom'],
            },
        ),
    ]
