# Generated by Django 5.0.2 on 2026-02-22 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='administration.produit'),
        ),
        migrations.AddField(
            model_name='salle',
            name='livreur_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'est_actif': True, 'role': 'LIVREUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salle_livreur1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salle',
            name='livreur_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'est_actif': True, 'role': 'LIVREUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salle_livreur2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secteur',
            name='chef_actif',
            field=models.OneToOneField(blank=True, limit_choices_to={'est_actif': True, 'role': 'CHEF_SECTEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secteur_supervise', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salle',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='administration.secteur'),
        ),
        migrations.AddField(
            model_name='horairecommande',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='administration.secteur'),
        ),
        migrations.AddField(
            model_name='variante',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='administration.produit'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom'], name='administrat_nom_aa594c_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie'], name='administrat_categor_556b94_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['est_actif'], name='administrat_est_act_2c9d22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('produit', 'nom')},
        ),
        migrations.AddIndex(
            model_name='secteur',
            index=models.Index(fields=['code'], name='administrat_code_94bed7_idx'),
        ),
        migrations.AddIndex(
            model_name='secteur',
            index=models.Index(fields=['est_actif'], name='administrat_est_act_ca5faf_idx'),
        ),
        migrations.AddIndex(
            model_name='salle',
            index=models.Index(fields=['code'], name='administrat_code_385c69_idx'),
        ),
        migrations.AddIndex(
            model_name='salle',
            index=models.Index(fields=['secteur', 'est_actif'], name='administrat_secteur_7118ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salle',
            unique_together={('secteur', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='horairecommande',
            unique_together={('secteur', 'jour_semaine')},
        ),
        migrations.AlterUniqueTogether(
            name='variante',
            unique_together={('produit', 'nom')},
        ),
    ]
