# Generated by Django 5.0.2 on 2026-03-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_produit_description_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_livraison_actif', models.BooleanField(default=True, verbose_name='Frais de livraison actifs')),
                ('frais_livraison_montant', models.DecimalField(decimal_places=2, default=0, help_text='En FCFA si type FIXE, en % si type POURCENTAGE', max_digits=10, verbose_name='Montant / taux de livraison')),
                ('frais_livraison_type', models.CharField(choices=[('FIXE', 'Montant fixe (FCFA)'), ('POURCENTAGE', 'Pourcentage du sous-total (%)')], default='FIXE', max_length=15, verbose_name='Type de frais livraison')),
                ('frais_orange', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage appliqué sur le montant total (livraison incluse)', max_digits=5, verbose_name='Frais Orange Money (%)')),
                ('frais_moov', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Frais Moov Money (%)')),
                ('frais_sank', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Frais Sank Money (%)')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Configuration tarifaire',
                'verbose_name_plural': 'Configuration tarifaire',
            },
        ),
    ]
