# Generated by Django 5.2.11 on 2026-04-03 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_configuration_taux_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='numero_moov',
            field=models.CharField(blank=True, default='', help_text='Numéro Moov Money configuré dans le dashboard Senfenico', max_length=20, verbose_name='Numéro Moov Money'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='numero_orange',
            field=models.CharField(blank=True, default='', help_text='Numéro Orange Money configuré dans le dashboard Senfenico', max_length=20, verbose_name='Numéro Orange Money'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='numero_sank',
            field=models.CharField(blank=True, default='', help_text='Numéro Sank Money configuré dans le dashboard Senfenico', max_length=20, verbose_name='Numéro Sank Money'),
        ),
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_senfenico', models.CharField(max_length=100, unique=True, verbose_name='Référence Senfenico')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('compte', models.CharField(choices=[('orange', 'Orange Money'), ('moov', 'Moov Money'), ('sank', 'Sank Money')], max_length=10, verbose_name='Compte destinataire')),
                ('statut', models.CharField(choices=[('processing', 'En cours'), ('in_transit', 'En transit'), ('success', 'Réussi'), ('cancelled', 'Annulé'), ('failed', 'Échoué')], default='processing', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('declenche_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_declenchés', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
