# Generated by Django 5.0.2 on 2026-04-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_add_horaires_ouverture_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='horaires_actifs',
            field=models.BooleanField(default=True, help_text="Décochez pour ignorer les horaires d'ouverture sans les supprimer", verbose_name='Horaires actifs'),
        ),
    ]
