# Generated by Django 6.0.5 on 2026-05-30 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_horaire_semaine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
            ],
            options={
                'verbose_name': 'Université',
                'verbose_name_plural': 'Universités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=200, verbose_name='Nom de la boutique')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('categorie_principale', models.CharField(choices=[('SANDWICH', 'Sandwich'), ('BOISSON', 'Boisson'), ('PATISSERIE', 'Pâtisserie'), ('SNACK', 'Snack'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie principale')),
                ('mode_livraison', models.CharField(choices=[('SOI_MEME', 'Livre soi-même'), ('LIVREUR', 'Fait appel à un livreur')], default='LIVREUR', max_length=10, verbose_name='Mode de livraison')),
                ('capacite_max_commandes', models.PositiveIntegerField(default=20, verbose_name='Capacité max commandes simultanées')),
                ('photo_cnib', models.ImageField(blank=True, null=True, upload_to='kyc/vendeurs/cnib/', verbose_name='Photo CNIB')),
                ('photo_visage', models.ImageField(blank=True, null=True, upload_to='kyc/vendeurs/visage/', verbose_name='Photo visage')),
                ('adresse_commerce', models.TextField(blank=True, null=True, verbose_name='Adresse du commerce')),
                ('horaires_disponibilite', models.JSONField(blank=True, default=dict, help_text='Ex: {"lundi": {"ouverture": "08:00", "fermeture": "18:00"}}', verbose_name='Horaires de disponibilité')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Compte validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Boutique active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeurs', to='administration.secteur', verbose_name='Emplacement (secteur/zone)')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_vendeur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeurs_valides', to=settings.AUTH_USER_MODEL)),
                ('universite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendeurs', to='administration.universite', verbose_name='Université desservie')),
            ],
            options={
                'verbose_name': 'Profil vendeur',
                'verbose_name_plural': 'Profils vendeurs',
                'ordering': ['nom_boutique'],
            },
        ),
        migrations.CreateModel(
            name='ProfilLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_cnib', models.ImageField(blank=True, null=True, upload_to='kyc/livreurs/cnib/', verbose_name='Photo CNIB')),
                ('photo_visage', models.ImageField(blank=True, null=True, upload_to='kyc/livreurs/visage/', verbose_name='Photo visage')),
                ('capacite_max_livraisons', models.PositiveIntegerField(default=5, verbose_name='Capacité max livraisons simultanées')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Compte validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livreur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreurs_valides', to=settings.AUTH_USER_MODEL)),
                ('zones_livraison', models.ManyToManyField(blank=True, related_name='livreurs_zones', to='administration.secteur', verbose_name='Zones de livraison')),
                ('universite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livreurs', to='administration.universite', verbose_name='Université')),
            ],
            options={
                'verbose_name': 'Profil livreur',
                'verbose_name_plural': 'Profils livreurs',
            },
        ),
        migrations.AddField(
            model_name='secteur',
            name='universite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secteurs', to='administration.universite', verbose_name='Université'),
        ),
    ]
