# Generated by Django 5.0.2 on 2026-08-28 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_add_universite_profils_vendeur_livreur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='administration.profilvendeur', verbose_name='Vendeur'),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='boutiques_attribuees',
            field=models.ManyToManyField(blank=True, related_name='livreurs_attribues', to='administration.profilvendeur', verbose_name='Boutiques attribuées'),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='compteur_abandon',
            field=models.PositiveIntegerField(default=0, verbose_name='Missions abandonnées'),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='en_service',
            field=models.BooleanField(db_index=True, default=False, verbose_name='En service'),
        ),
        migrations.CreateModel(
            name='CreneauLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: 10h00, 12h30', max_length=50, verbose_name='Libellé')),
                ('heure', models.TimeField(verbose_name='Heure du créneau')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(db_index=True, default=True, verbose_name='Créneau actif')),
                ('universite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_livraison', to='administration.universite', verbose_name='Université (vide = global)')),
            ],
            options={
                'verbose_name': 'Créneau de livraison',
                'verbose_name_plural': 'Créneaux de livraison',
                'ordering': ['ordre', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Action')),
                ('cible_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Type de cible')),
                ('cible_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la cible')),
                ('details', models.TextField(blank=True, default='', verbose_name='Détails')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': "Entrée du journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['action', 'date_creation'], name='administrat_action_1ed176_idx')],
            },
        ),
    ]
